id: I99D293AA
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T22:04:59.606722'
last_modified: '2022-05-30T22:04:59.606732'
parser: null
source_metadata:
  title: Khandro Tāre Lhamo Series
  language: en
  description: 'Texts by and about Khandro Tāre Lhamo (tA re lha mo, 1938–2003), who
    was one of the most prominent tertöns of recent times:'
  volume:
    f1D24:
      title: Prayer for the Long Life of Khandro Tāre Lhamo
      base_file: f1D24.txt
      order: 1
      parent: Long Life Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
